---
version: "3.5"
services:

  writefreely:
    image: judohippo/writefreely:0.0.2
    container_name: writefreely
    ports:
      - 6111:80
      - 6112:443
    # depends_on:
    #   - nginx-blog
    restart: unless-stopped

  nginx-blog:
    image: nginx:stable-alpine
    container_name: nginx-blog
    restart: always
    ports:
      - '4480:80'
      - '4443:443'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../proxy/letsencrypt:/etc/letsencrypt
    # networks:
    #   - proxy_proxynet
